services:
  - type: web
    name: nadle-backend
    runtime: docker
    envVars:
      - key: BIKE_API_KEY
        sync: false
      - key: TOUR_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: STORE_API_KEY
        sync: false
